const Product = [
  {
    id: 1,
    title: "Happy",
    expression: "😊",
    description: "Hello, my name is Happy and you can tell that I am happy.",
    price: 4.99,
    category: "Emotions",
    stock: 150,
    rating: 4.5,
    tags: ["joy", "smile", "positive"],
    imageUrl: "https://example.com/images/happy.png",
    manufacturer: "EmotionCo",
    releaseDate: "2023-01-15",
  },
  {
    id: 2,
    title: "V. Happy",
    expression: "😁",
    description: "Hello, my name is V. Happy, I am happier than Happy.",
    price: 9.99,
    category: "Emotions",
    stock: 100,
    rating: 4.7,
    tags: ["joy", "big smile", "very positive"],
    imageUrl: "https://example.com/images/vhappy.png",
    manufacturer: "EmotionCo",
    releaseDate: "2023-03-22",
  },
  {
    id: 3,
    title: "Sad",
    expression: "😢",
    description: "I am Saddy, I am sometimes happy but sad at the moment.",
    price: 1.99,
    category: "Emotions",
    stock: 200,
    rating: 3.8,
    tags: ["sadness", "tear", "blue"],
    imageUrl: "https://example.com/images/sad.png",
    manufacturer: "EmotionCo",
    releaseDate: "2023-02-10",
  },
  {
    id: 4,
    title: "Excited",
    expression: "😃",
    description: "I am Excito, always ready for new adventures!",
    price: 5.99,
    category: "Emotions",
    stock: 120,
    rating: 4.6,
    tags: ["enthusiasm", "energy", "happy"],
    imageUrl: "https://example.com/images/excited.png",
    manufacturer: "EmotionCo",
    releaseDate: "2023-04-05",
  },
  {
    id: 5,
    title: "Angry",
    expression: "😠",
    description: "I am Angry, sometimes things don’t go my way.",
    price: 3.49,
    category: "Emotions",
    stock: 80,
    rating: 3.2,
    tags: ["frustration", "irritation", "red"],
    imageUrl: "https://example.com/images/angry.png",
    manufacturer: "EmotionCo",
    releaseDate: "2023-05-18",
  },
  {
    id: 6,
    title: "Surprised",
    expression: "😮",
    description: "I am Surprise, always caught off guard!",
    price: 2.99,
    category: "Emotions",
    stock: 160,
    rating: 4.0,
    tags: ["astonishment", "shock", "wide eyes"],
    imageUrl: "https://example.com/images/surprised.png",
    manufacturer: "EmotionCo",
    releaseDate: "2023-06-30",
  },
  {
    id: 7,
    title: "Calm",
    expression: "😌",
    description: "I am Calm, here to bring peace and tranquility.",
    price: 6.49,
    category: "Emotions",
    stock: 140,
    rating: 4.8,
    tags: ["peace", "serenity", "relaxation"],
    imageUrl: "https://example.com/images/calm.png",
    manufacturer: "EmotionCo",
    releaseDate: "2023-07-12",
  },
  {
    id: 8,
    title: "Confused",
    expression: "😕",
    description: "I am Confuso, often puzzled by things around me.",
    price: 2.49,
    category: "Emotions",
    stock: 110,
    rating: 3.5,
    tags: ["puzzled", "uncertain", "perplexed"],
    imageUrl: "https://example.com/images/confused.png",
    manufacturer: "EmotionCo",
    releaseDate: "2023-08-20",
  },
  {
    id: 9,
    title: "Loving",
    expression: "😍",
    description: "I am Lovey, filled with love and affection.",
    price: 7.99,
    category: "Emotions",
    stock: 130,
    rating: 4.9,
    tags: ["affection", "heart", "care"],
    imageUrl: "https://example.com/images/loving.png",
    manufacturer: "EmotionCo",
    releaseDate: "2023-09-05",
  },
  {
    id: 10,
    title: "Sleepy",
    expression: "😴",
    description: "I am Sleepo, always ready to take a nap.",
    price: 3.99,
    category: "Emotions",
    stock: 170,
    rating: 4.2,
    tags: ["tired", "rest", "drowsy"],
    imageUrl: "https://example.com/images/sleepy.png",
    manufacturer: "EmotionCo",
    releaseDate: "2023-10-11",
  },
];

export default Product;
